# Generated by Django 5.2.5 on 2025-08-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('I', 'Incomplete'), ('O', 'Ongoing'), ('C', 'Completed')], default='I', max_length=1)),
                ('tag', models.CharField(choices=[('S', 'Shopping'), ('W', 'work'), ('O', 'Other'), ('A', 'All')], default='A', max_length=1)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
