# Generated by Django 5.2.5 on 2025-08-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('I', 'Incomplete'), ('C', 'Completed')], default='I', max_length=1),
        ),
    ]
